server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: forest-pest-control-system
  profiles:
    active: dev
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 跨域配置
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
  allowed-methods: 
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# JWT配置
jwt:
  secret: forestPestControlSystemSecretKey2024
  expiration: 86400000 # 24小时

# 模拟数据配置
mock-data:
  enabled: true
  user-count: 10
  pest-count: 50
  pesticide-count: 30
  treatment-plan-count: 20

# 日志配置
logging:
  level:
    com.forestpest: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"